### ISSUE TITLE
Token Error

### ISSUE THREAD

**Issue by SrCobayo** [Kilvoctu/aiyabot#102]
D:\- Descargas\aiyabot-main>python -m venv venv

D:\- Descargas\aiyabot-main>venv\Scripts\pip.exe install -r requirements.txt
Requirement already satisfied: py-cord in d:\- descargas\aiyabot-main\venv\lib\site-packages (from -r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: python-dotenv in d:\- descargas\aiyabot-main\venv\lib\site-packages (from -r requirements.txt (line 2)) (0.21.1)
Requirement already satisfied: requests in d:\- descargas\aiyabot-main\venv\lib\site-packages (from -r requirements.txt (line 3)) (2.28.2)
Requirement already satisfied: Pillow in d:\- descargas\aiyabot-main\venv\lib\site-packages (from -r requirements.txt (line 4)) (9.4.0)
Requirement already satisfied: tomlkit in d:\- descargas\aiyabot-main\venv\lib\site-packages (from -r requirements.txt (line 5)) (0.11.6)
Requirement already satisfied: typing-extensions<5,>=4 in d:\- descargas\aiyabot-main\venv\lib\site-packages (from py-cord->-r requirements.txt (line 1)) (4.4.0)
Requirement already satisfied: aiohttp<3.9.0,>=3.6.0 in d:\- descargas\aiyabot-main\venv\lib\site-packages (from py-cord->-r requirements.txt (line 1)) (3.8.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\- descargas\aiyabot-main\venv\lib\site-packages (from requests->-r requirements.txt (line 3)) (1.26.14)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\- descargas\aiyabot-main\venv\lib\site-packages (from requests->-r requirements.txt (line 3)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in d:\- descargas\aiyabot-main\venv\lib\site-packages (from requests->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\- descargas\aiyabot-main\venv\lib\site-packages (from requests->-r requirements.txt (line 3)) (2022.12.7)
Requirement already satisfied: frozenlist>=1.1.1 in d:\- descargas\aiyabot-main\venv\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.3.3)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in d:\- descargas\aiyabot-main\venv\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\- descargas\aiyabot-main\venv\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.8.2)
Requirement already satisfied: aiosignal>=1.1.2 in d:\- descargas\aiyabot-main\venv\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in d:\- descargas\aiyabot-main\venv\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (22.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\- descargas\aiyabot-main\venv\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (6.0.4)

[notice] A new release of pip available: 22.2.1 -> 23.0
[notice] To update, run: D:\- Descargas\aiyabot-main\venv\Scripts\python.exe -m pip install --upgrade pip

D:\- Descargas\aiyabot-main>venv\Scripts\python.exe aiya.py
Using URL: http://127.0.0.1:7860
Using outputs directory: outputs
[2023-02-11 15:52:09] INFO: Cleaning up tasks.
[2023-02-11 15:52:09] INFO: Closing the event loop.
[2023-02-11 15:52:09] ERROR: token must be of type str, not NoneType

Sorry if i need to give another type of information, is my first time opening an issue.

**Comment by Kilvoctu** [comment]
Hi @SrCobayo, you need to put in your bot token to run the bot

Please review the set up instructions 
https://github.com/Kilvoctu/aiyabot#setup-requirements

If you need help on setting up a Discord bot, I have a brief guide or you can find a more in-depth on YouTube or somewhere
https://github.com/Kilvoctu/aiyabot/wiki/Setting-up-a-Discord-bot

**Comment by SrCobayo** [comment]
![image](https://user-images.githubusercontent.com/125153007/218276650-2168f323-94ee-4e34-9a13-d7e1adc12086.png)
![image](https://user-images.githubusercontent.com/125153007/218276675-f024fd64-ed6b-4a04-8605-f93e9bad85c0.png)

**Comment by Kilvoctu** [comment]
Is .env in the repo's root folder, next to aiya.py? The error is saying that it can't find the bot token.

**Comment by SrCobayo** [comment]
![image](https://user-images.githubusercontent.com/125153007/218279117-fbf04b48-025c-4cee-b8e5-542eb4e6a7fd.png)

**Comment by Kilvoctu** [comment]
I'm seeing now that your OS thinks the .env is another text file instead of recognizing it as a .env file. This is how it looks on mine
![image](https://user-images.githubusercontent.com/2993060/218281387-fd589f13-5c8c-4e37-b4ac-4f5f7411562e.png)
Can you check if the file is `.env` and not something like `.env.txt`. You can confirm by showing file extensions in folder options
![image](https://user-images.githubusercontent.com/2993060/218281472-31506c95-b8ee-4824-afc9-7b50f07a5f85.png)

**Comment by SrCobayo** [comment]
That was the issue! Thank you so much. :D

**Comment by Kilvoctu** [comment]
No problem, glad you got it working 👍 
Think it was my fault, I was a bit unclear on the readme (I adjusted my wording on it now)
