### ISSUE TITLE
Discord channel permissions are only partially honored?

### ISSUE THREAD

**Issue by VictorZakharov** [Kilvoctu/aiyabot#104]
I want to set up a single discord channel for stable diffusion generation which will have slow mode enabled, so the bot will not respond to prompts on any other channel, to keep things nicely organized.

I disallowed the bot to see/post channel content, but it still reacts to slash commands and will attempt to generate an image, failing to post a reply with an image due to 403. It should not even attempt to generate or reply "bear with me", just ignore, since it's not shown in the members list.

**Comment by Kilvoctu** [comment]
Heya, for bot channel management this is handled by Discord. On your server, go to the Server Settings, then Integrations.  
You'll see your bot listed there, click on Manage next to it
![image](https://user-images.githubusercontent.com/2993060/218333487-8d0f04a5-21a9-4e90-a7ea-2505f94d98ca.png)

On the next screen, you can set up various permissions. You'll want to review the channel permissions. This is how mine looks for example
![image](https://user-images.githubusercontent.com/2993060/218333534-c45f25f9-a4b7-4749-847d-a403b0258c48.png)

**Comment by VictorZakharov** [comment]
@Kilvoctu Yes, I have it configured like this:
![image](https://user-images.githubusercontent.com/8978766/218337126-0f6e939e-0007-4b85-8373-128fa229cf51.png)
But it has no effect on anything. Literally nothing happened after I set it up like this. Only after I changed each channel permission here:
![image](https://user-images.githubusercontent.com/8978766/218337148-079cb93d-bc52-43f6-928f-3ce43a5b97ca.png)
![image](https://user-images.githubusercontent.com/8978766/218337150-b2c0633f-02e1-421a-ad0d-eada82adbee9.png)
And revoked all permissions for the bot, then it stopped generating images. But it still responds with its usual "please wait for result" message.

**Comment by Kilvoctu** [comment]
You don't need to touch the individual channel permissions, it'll generally cause issues. Discord intends slash bot management to be done with the integrations screen.

> But it has no effect on anything. Literally nothing happened after I set it up like this.

Other people are still able to see the commands, even with those settings? Note that as admin, you have access to everything regardless of permission settings. With my above settings, this is how it looks to non-admin
![image](https://user-images.githubusercontent.com/2993060/218337717-4f857b44-e36a-409a-97bd-e920206e97b0.png)

**Comment by VictorZakharov** [comment]
@Kilvoctu You are right, it works. I didn't realize that because I'm admin, permissions work in somewhat unexpected ways.
![image](https://user-images.githubusercontent.com/8978766/218339428-25447fee-52f1-4c82-bc96-0f6172dbb123.png)
So I removed all channel permission overrides, and set this:
![image](https://user-images.githubusercontent.com/8978766/218339461-7d3ce5b8-344d-4273-9c68-1b5b4cdbbbfd.png)
![image](https://user-images.githubusercontent.com/8978766/218339470-eea70340-b8ca-4854-8cc3-189a5f433657.png)
Then logged in as role "everyone" and checked that users can only post to stable-diffusion channel where slow mode is enabled. Thanks! I think you can add this to your wiki under "permissions".

**Comment by Kilvoctu** [comment]
Nice, glad you got it sorted out. 👍 I'll find a place to put it into the wiki.

Also, I have been looking at #103. Will have an answer shortly.
