### ISSUE TITLE
changing the maximum resolution does not work

### ISSUE THREAD

**Issue by IWULII** [Kilvoctu/aiyabot#110]
I changed the value already in all the files that my hands got to, but the choice was a maximum of 1024 and remained

**Comment by Kilvoctu** [comment]
There shouldn't be more than one file to change. The value to edit is `max_size` in config.toml.  
After that, you need to restart the aiyabot. Discord does not by default update option choices dynamically.

**Comment by IWULII** [comment]
![Снимок экрана 2023-02-18 004221](https://user-images.githubusercontent.com/124499205/219800382-943be163-778e-49cc-8a15-63484586d93c.png)
![Снимок экрана 2023-02-18 004251](https://user-images.githubusercontent.com/124499205/219800403-6a6d7650-da0f-4139-8371-810970c79d14.png)
Work on redraw...
![Снимок экрана 2023-02-18 004917](https://user-images.githubusercontent.com/124499205/219800474-fb545844-ca57-4aba-8dd0-568ecf0b4985.png)

**Comment by IWULII** [comment]
> Heya, Discord is just dumb and slow on updating. I recorded a video showing how to remind Discord to update the value. It's a Discord issue. https://streamable.com/rrmmws Basically you have to try in a different channel before Discord wake up and realizes.

reinstalled windows and it worked
is it possible to somehow remove the bot functions that I don't need?

**Comment by Kilvoctu** [comment]
That was extreme, but glad it worked for you, lol. 

There's no feature to remove any of slash command options if that's what you mean. This is in my list at #85 , but I think Discord will not allow such a function.
