### ISSUE TITLE
Performance issue? 4.5sec to generate, 11-15 seconds to post

### ISSUE THREAD

**Issue by VictorZakharov** [Kilvoctu/aiyabot#111]
**Describe the bug**  
On my machine it takes between 4-4.5sec to generate an image with 30 steps, and an additional 6-10sec for the bot to post it.
I have a 1000/50M internet connection. Is this a bug, a limitation of discord (it throttles all bot messages) or a config issue? I would think total bot overhead should be <1sec.

Any way I can troubleshoot this more to provide better breakdown of where the time is going?

My processor is Ryzen 9 5900x, PC was not doing any other tasks at the time, no running backups in the background etc.

---

**Environment**
 - OS: Windows 10.

**Comment by Kilvoctu** [comment]
Heya, Victor. It's Discord throttling or doing whatever they're doing to uploaded attachments from bots.

This specific issue was handled by PR #89. I went through and did a quick benchmark on each step.

<details>This grabs the image and makes the message that will be posted to Discord. A second thread is created to manage this.  
Note that by not including the attachment (changing `files=files` to `files=''`), AIYA will have no issue posting immediately.

<summary>Constructing the message</summary>
<br>

![image](https://user-images.githubusercontent.com/2993060/219902494-88a4cd20-e2b3-4b29-8cb2-9b5aeb3a7523.png)

</details><details>This adds workers to the thread as needed.
<summary>Thread</summary>
<br>

![image](https://user-images.githubusercontent.com/2993060/219902587-dbe70786-01f4-4f36-b90d-228184658a63.png)

</details><details>This manages the queue of posts.
<summary>Queue</summary>
<br>

![image](https://user-images.githubusercontent.com/2993060/219902545-6a4f99f9-94ef-4c73-b78a-bf3319b5a2e2.png)

</details>

The time to execute each task in the thread is really random as you've observed, which adds credence to it being mostly on Discord side. I've had some images post immediately, while others take ~10s, all in the same queue.  
However, the main idea is that posting is independent from image generation (as explained in #89). The benefit of this is noticeable as the number of users scale up.  

Idunno if there's any way to get Discord to process the attachment faster.

**Comment by VictorZakharov** [comment]
@Kilvoctu You are right, it's random, anywhere from 3sec to 15sec for me.
It's not dependent on image size. I tried 256x256 and 512x512, with a single step.
There is no reasonable explanation since a 256x256 image is pretty small, around 100KB.
I could also get it if I was hitting Discord with dozens of requests per second. Here it's just 1 request per minute or smth.

Oh well, thanks for explaining, and thanks for sharing screenshots from an IntelliJ IDE (PyCharm?).
It seems that VS Code is the default choice for most folks who will stick with it for much longer than necessary. I will sleep better knowing other people are also enjoying IntelliJ editors.

**Comment by Kilvoctu** [comment]
Yeah I did the same tests earlier too. I feel like there's certain intervals in which Discord will process what bots are sending to it, as sometimes I notice it'll post a bunch of queued images at once. Not 100% sure what is going on with the Discord side.

Also, yea it is PyCharm. In Discussions, I revealed that this project is my first time touching Python (and I'm non-programmer). I'd started out just using Notepad++ lol 😅.  
My friend who is programmer by profession fiercely recommended PyCharm to me, and there's no way AIYA could have been developed this far without it.

**Comment by VictorZakharov** [comment]
@Kilvoctu I'm using IntelliJ tools since 2015, they are really good. It's a mystery how so few people know about it. If you are a non-programmer using python, you must be using ChatGPT pretty heavily. Is this your secret?

**Comment by Kilvoctu** [comment]
No I've never used ChatGPT.  
It was mostly general learning by reading/watching tutorials, reading documentation, and countless visits to stackoverflow. My secret is just being motivated and trying really hard 😅

**Comment by Kilvoctu** [comment]
There may be some additional innovative ways to improve the posting-to-discord performance. However, I'll be closing this issue as it's been addressed in the previously mentioned PR.
