### ISSUE TITLE
Bot breaks with "invalid parameter"

### ISSUE THREAD

**Issue by T9es** [Kilvoctu/aiyabot#114]
The issue:

The bot itself will break sometimes for no apparent reason. It will spew out "an invalid parameter was found" even though the prompt did not have anything changed in it, as well as the settings (From when the prompt was working).

```
Ignoring exception in command draw:
Traceback (most recent call last):
  File "Y:\AI-GIT-CLONE\aiyabot\venv\lib\site-packages\discord\commands\core.py", line 124, in wrapped
    ret = await coro(arg)
  File "Y:\AI-GIT-CLONE\aiyabot\venv\lib\site-packages\discord\commands\core.py", line 978, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "Y:\AI-GIT-CLONE\aiyabot\core\stablecog.py", line 319, in dream_handler
    await ctx.send_response(
  File "Y:\AI-GIT-CLONE\aiyabot\venv\lib\site-packages\discord\interactions.py", line 825, in send_message
    await self._locked_response(
  File "Y:\AI-GIT-CLONE\aiyabot\venv\lib\site-packages\discord\interactions.py", line 1090, in _locked_response
    await coro
  File "Y:\AI-GIT-CLONE\aiyabot\venv\lib\site-packages\discord\webhook\async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Y:\AI-GIT-CLONE\aiyabot\venv\lib\site-packages\discord\bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "Y:\AI-GIT-CLONE\aiyabot\venv\lib\site-packages\discord\commands\core.py", line 375, in invoke
    await injected(ctx)
  File "Y:\AI-GIT-CLONE\aiyabot\venv\lib\site-packages\discord\commands\core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
```
From the error, I'd guess it has something to do with my internet, but it still does not explain why the back msg goes through discord

Note, the code above appears in the command line, but sometimes, JUST SOMETIMES everything works. (The bot still spew out errors and says that app is unavailable, but the command goes through to the AI interface)

Windows 10 pro edition, git clone

**Comment by Kilvoctu** [comment]
What was the last prompt that was entered before you got this error? Were you using the slash command (/draw), or a button. I'll need more information to understand why this happens before I can look into any solutions.
   
The log does seem to be network related; slash command bots need to follow-up with Discord to a command within 3 seconds or else it errors out. This is independent from it communicating with the Web UI.

**Comment by T9es** [comment]
More info:

/draw was used with a prompt of: *swimsuit, beach, sand, water* as a test. This caused the error.
After the error was present, no /draw command worked, even img2img draw or even a simple thing like /identify. Breaks occur at random times, sometimes setting the strength caused it to freeze up.

Oh, in the case of the 3 seconds I have no clue then what caused this, but switching up my internet connections happened to fix it, however, this can be unrelated and just a random occurrence

**Comment by Kilvoctu** [comment]
> More info:
> 
> /draw was used with a prompt of: _swimsuit, beach, sand, water_ as a test. This caused the error. After the error was present, no /draw command worked, even img2img draw or even a simple thing like /identify. Breaks occur at random times, sometimes setting the strength caused it to freeze up.

Heya, when you say error, you mean `An invalid parameter was found!`? This is my exception handler error when the backend (Web UI) does not generate a response. The most common reason is when a value is entered that can't be interpreted by the API. You can see me replicating it here by entering a letter for `strength`.  
![image](https://user-images.githubusercontent.com/2993060/220003451-e7947794-87c1-4a89-aae5-08052e7118e5.png)

That said, AIYA is supposed to be able to continue normally afterward, as can be seen from the screenshot. After you submit a /draw command, how long does it take to get the initial reply?

When AIYA stops responding, is `Application Command raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction` the last thing that appears in the console log?

**Comment by Kilvoctu** [comment]
> update: Switching channels fixes it. For some reason it feels like it's also the settings issue, however, every channel has the same settings so that makes no sense.

Are you changing /settings or config.toml during operation? If so, what are you trying to change? As can be seen in https://github.com/Kilvoctu/aiyabot/issues/110#issuecomment-1435358048, there are some settings that Discord hates to change on the fly. I can try to mitigate what I can.

**Comment by T9es** [comment]
![image](https://user-images.githubusercontent.com/107748212/220004421-d36fd1f8-b10e-4865-a037-f42523c3ed6e.png)

This the exact console screenshot. The invalid parameter does make sense, however, it breaks at random with no setting being changed or wrong parameters being typed into the wrong places. I've double checked the settings on the channels that broke.

I'm changing /settings by hand through discord. Config.toml is left without any changes. I'm changing width, height, steps, max steps, sampler, strength, count, max count, negative prompts... and that's about it I think. I'm not using any values that are outside of the discord suggestions

**Comment by T9es** [comment]
Here are the channel settings at the time of break
![image](https://user-images.githubusercontent.com/107748212/220005002-79386ff5-d9f1-4389-b0fc-ae3b781ca086.png)

**Comment by Kilvoctu** [comment]
For `strength`, the Web UI I believe will only accept the `.` as decimal, not `,`. Give me a bit, I'll include a `,` to `.` conversion so people can use their desired decimal

**Comment by T9es** [comment]
Oh yeah, that seemed to be the issue.... dear god how much sweat and tears have gone into trying to fix this on my own, and it's just a dumb , or . difference. Thank you!

**Comment by Kilvoctu** [comment]
lol, no problem. Many times 95% of the effort is spent finding the cause, with remaining 5% on the solution.  
I pushed 6eed45141610b49fe20e315b674fcaea2cd7e851 which should allow usage as `,` for decimals.
