### ISSUE TITLE
I want to add the model in the model.csv but it got error

### ISSUE THREAD

**Issue by idmakers** [Kilvoctu/aiyabot#116]
Hello I want to add the model list to change by discord bot
but I got some error, when I edit the model.csv

below is the model.csv
display_name|model_full_name|activator_token
default||
SD1.5|v1-5-pruned.ckpt|
wd1.4|wd-1-4-anime_e2.ckpt|
anything4.5|anything-v4.5.ckpt|

and below is the error after the file change
`Traceback (most recent call last):`
` File "F:\aiyabot\aiya.py", line 19, in <module`
 `settings.files_check()`
  `File "F:\aiyabot\core\settings.py", line 320, in files_check`
  `  populate_global_vars()`
  `File "F:\aiyabot\core\settings.py", line 417, in populate_global_vars`
  ` if row[1].split(os.sep)[-1] == model['filename'].split(os.sep)[-1] \`
`IndexError: list index out of range`

**Comment by Kilvoctu** [comment]
Heya, I assume you meant to say `models.csv`. There is no `model.csv`, and if you made one AIYA will not read from it.  

I can't replicate this issue. AIYA seems to have some issue parsing the `models.csv`. If you use the default `models.csv`, does she load correctly?
