### ISSUE TITLE
Keyerror: 'info'

### ISSUE THREAD

**Issue by bloodk1n** [Kilvoctu/aiyabot#12]
After pulling the latest commit, the bot stucks at saving images' metadata. 
Error message are as follows: 
```python
Traceback (most recent call last):
  File "C:\Users\leo89\Desktop\aipaint\aiyabot\core\stablecog.py", line 239, in dream
    metadata = json.dumps(response['info']).strip('"')
KeyError: 'info'
```

**Comment by Kilvoctu** [comment]
Well I think I see now that any time the code get any response from api, it doesn't want to read it for you 🤔, and you said before it's not crlf issue.
You are still trying to run the bot on Python 3.10.6, Windows 11, Trad. Chinese system? And I think you're going through gradio auth, right, not localhost?

**Comment by bloodk1n** [comment]
> 

Yes, the environments are untouched.
The bot goes through gradio auth via specified hostname, but i'll try to let the bot send api requests via 127.0.0.1.

**Comment by bloodk1n** [comment]
After mapping the url to 127.0.0.1, the problem solved itself.
