### ISSUE TITLE
FaceFix breaks edit

### ISSUE THREAD

**Issue by Advtech92** [Kilvoctu/aiyabot#122]
**Describe the bug**  
When editing a prompt/redoing the prompt, this appears:
![Error](https://user-images.githubusercontent.com/2319526/220808389-aca3fe1a-6a97-4e24-9898-2df82c6013ff.png)
It is set as NONE, but does not proceed past that point. Users were also saying they were having issues when attempting to set it to use one or the other options other than none. The only working fix to allow it to proceed was to remove it entirely.
---

**Environment**
 - OS: [e.g. Windows / Linux]
Windows 10 Professional, Python 3.10.6, NVIDIA 960

**Comment by Kilvoctu** [comment]
Hi this was fixed with https://github.com/Kilvoctu/aiyabot/commit/d2b1c0890b124615776497b35a4192e07fa3cec0. Did you update to this commit yet?

**Comment by Advtech92** [comment]
I did update but I can't confirm if that fixed the error because now I am getting this:
```Traceback (most recent call last):
  File "E:\Downloads\Attempt at SD\DiscordBot\aiyabot\venv\lib\site-packages\discord\commands\core.py", line 124, in wrapped
    ret = await coro(arg)
  File "E:\Downloads\Attempt at SD\DiscordBot\aiyabot\venv\lib\site-packages\discord\commands\core.py", line 976, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "E:\Downloads\Attempt at SD\DiscordBot\aiyabot\core\stablecog.py", line 296, in dream_handler
    batch_check = settings.batch_format(batch)
  File "E:\Downloads\Attempt at SD\DiscordBot\aiyabot\core\settings.py", line 115, in batch_format
    format_batch_string = batch_string.replace(".", ",").split(",")
AttributeError: 'int' object has no attribute 'replace'```

**Comment by Kilvoctu** [comment]
You can confirm by seeing if the option appears in the /draw command
![image](https://user-images.githubusercontent.com/2993060/221102130-516143e8-e950-4b31-b0c8-c00f197648f7.png)

This looks like an unrelated error in regards to my recent change to the count/batch option. What is the steps you took before getting this issue? I understand what this error is trying to tell me but I'd like to know how to reproduce this issue.

**Comment by Advtech92** [comment]
Updated to the latest on main, and
```Traceback (most recent call last):
  File "E:\Downloads\Attempt at SD\DiscordBot\aiyabot\venv\lib\site-packages\discord\commands\core.py", line 124, in wrapped
    ret = await coro(arg)
  File "E:\Downloads\Attempt at SD\DiscordBot\aiyabot\venv\lib\site-packages\discord\commands\core.py", line 976, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "E:\Downloads\Attempt at SD\DiscordBot\aiyabot\core\stablecog.py", line 296, in dream_handler
    batch_check = settings.batch_format(batch)
  File "E:\Downloads\Attempt at SD\DiscordBot\aiyabot\core\settings.py", line 116, in batch_format
    format_batch_string = batch_string.replace(".", ",").split(",")
AttributeError: 'int' object has no attribute 'replace'```

Also, can you include a way to better log when people are generating photos? I had someone invite my bot to their server and since I had to reboot my CMD, all I know is their guild, no clue who generated the images.

**Comment by Kilvoctu** [comment]
Huh, I specifically cast any deprecated values to `str` with https://github.com/Kilvoctu/aiyabot/commit/a12db7b4ad6b83c7f9d7fcb91db7445a2327a8b8

What does your channel json look like?

> Also, can you include a way to better log when people are generating photos? I had someone invite my bot to their server and since I had to reboot my CMD, all I know is their guild, no clue who generated the images.

Every /draw, 🖋️ and 🎲 command includes the name and discriminator of the user who generated the image. It was added since https://github.com/Kilvoctu/aiyabot/commit/6d497827e714a12c1ef1038818c1b0c71ba3b97e

Are you sure you pulled to the latest commit?

**Comment by Advtech92** [comment]
I know for sure I updated. (Did a git reset --hard then a pulled out again) now I am getting outdated commands and can't use the bot at all.

**Comment by Kilvoctu** [comment]
What does your channel json look like?

Outdated commands is a Discord issue. This similar issue in my wiki faq talks about it https://github.com/Kilvoctu/aiyabot/wiki/Frequently-asked-questions-and-other-tips-(setup)#changes-to-max_size-does-nothing

**Comment by Advtech92** [comment]
Deleting the JSON fixed the issue. I'll set back up the defaults I had later. I am guessing that's what causing the issue. Thanks for the fixes. Looking forward to the better logging.
