### ISSUE TITLE
Bot not starting

### ISSUE THREAD

**Issue by Kaylandar** [Kilvoctu/aiyabot#124]
**Describe the bug**  
launch.sh does not start the bot.
Automatic1111 is installed and running correctly.
I've tried to replace pythn and pip in launch.sh with phython3 and pip3, but it still didn't work.

./launch.sh 
/usr/bin/python: No module named venv
./launch.sh: line 4: ./venv/bin/activate: No such file or directory
Requirement already satisfied: py-cord in /home/butter/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: python-dotenv in /home/butter/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.0.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.25.1)
Requirement already satisfied: Pillow in /home/butter/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (9.4.0)
Requirement already satisfied: tomlkit in /home/butter/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (0.11.6)
Requirement already satisfied: aiohttp<3.9.0,>=3.6.0 in /home/butter/.local/lib/python3.9/site-packages (from py-cord->-r requirements.txt (line 1)) (3.8.4)
Requirement already satisfied: typing-extensions<5,>=4 in /home/butter/.local/lib/python3.9/site-packages (from py-cord->-r requirements.txt (line 1)) (4.5.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/butter/.local/lib/python3.9/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in /home/butter/.local/lib/python3.9/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in /home/butter/.local/lib/python3.9/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.3.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/butter/.local/lib/python3.9/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.8.2)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /home/butter/.local/lib/python3.9/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in /home/butter/.local/lib/python3.9/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (22.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/butter/.local/lib/python3.9/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (6.0.4)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (2.10)
  File "aiya.py", line 32
    async def stats(ctx):
        ^
SyntaxError: invalid syntax

---

**Environment**
Debian 5.10.162-1 
python --version
Python 2.7.18

python3 --version
Python 3.9.2

**Comment by Kilvoctu** [comment]
Heya, unfortunately I don't have any linux knowledge. A linux user helped me add that support for AIYA, and it works for them... 

The syntax error seems to be due to unsupported older python version. async seems to be from python 3.7 but AIYA actually requires 3.10 due to some other code. Are you able to update to that?

**Comment by Kaylandar** [comment]
Hi,
I've compiled 3.10, and installed alongside 3.9 (with make altinstall)
I've modified the script launch.sh

!/bin/bash
python3.10 -m venv venv

source ./venv/bin/activate
pip3.10 install -r requirements.txt

python3.10 aiya.py



Unfortunately now I get:

./launch.sh 
Requirement already satisfied: py-cord in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: python-dotenv in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.0.0)
Requirement already satisfied: requests in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (2.28.2)
Requirement already satisfied: Pillow in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (9.4.0)
Requirement already satisfied: tomlkit in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (0.11.6)
Requirement already satisfied: aiohttp<3.9.0,>=3.6.0 in ./venv/lib/python3.10/site-packages (from py-cord->-r requirements.txt (line 1)) (3.8.4)
Requirement already satisfied: typing-extensions<5,>=4 in ./venv/lib/python3.10/site-packages (from py-cord->-r requirements.txt (line 1)) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.10/site-packages (from requests->-r requirements.txt (line 3)) (3.0.1)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.10/site-packages (from requests->-r requirements.txt (line 3)) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.10/site-packages (from requests->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests->-r requirements.txt (line 3)) (1.26.14)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv/lib/python3.10/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (6.0.4)
Requirement already satisfied: aiosignal>=1.1.2 in ./venv/lib/python3.10/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./venv/lib/python3.10/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in ./venv/lib/python3.10/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.8.2)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.10/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (22.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./venv/lib/python3.10/site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.3.3)

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
Fetching origin
On branch main
Your branch is behind 'origin/main' by 4 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   launch.sh

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	botenv.env

no changes added to commit (use "git add" and/or "git commit -a")
Using URL: http://127.0.0.1:7860
Using outputs directory: outputs
[2023-02-24 17:40:32] INFO: Cleaning up tasks.
[2023-02-24 17:40:32] INFO: Closing the event loop.
[2023-02-24 17:40:32] ERROR: token must be of type str, not NoneType

**Comment by Kilvoctu** [comment]
> [2023-02-24 17:40:32] ERROR: token must be of type str, not NoneType

This tells me AIYA is not seeing the bot token. Do you have a .env file in the root directory containing `TOKEN = your bot token`

**Comment by Kilvoctu** [comment]
It's just `.env`, like this
![image](https://user-images.githubusercontent.com/2993060/221225476-29fb86f8-1ccf-4464-a5fa-bbcf19f4df28.png)

**Comment by Kaylandar** [comment]
It works. I think I had a stupid moment :)! 
Thanks a lot. 
( python still needs to be 3.10, it doesn't work with 3.9 even after changing file name)

**Comment by Kilvoctu** [comment]
Glad you got it working 👍👍  

And yea, AIYA used to work with 3.9, but got bumped up to 3.10 last month due to something I needed to add to make her process queue faster; think it's specifically this line https://github.com/Kilvoctu/aiyabot/blob/becf0c224fbe10a9c6d9ffafc17075e9f0acc1c8/core/queuehandler.py#L77
