### ISSUE TITLE
models.csv weird behavior

### ISSUE THREAD

**Issue by Comdriver** [Kilvoctu/aiyabot#137]
Hi!
Trying to add all my models to the list following the [Wiki](https://github.com/Kilvoctu/aiyabot/wiki/Model-swapping)
My current models.csv  is:
```
display_name|model_full_name|activator_token
SD 1.5|stable_diffusion_v1.5.ckpt|
SD 1.4|stable_diffusion_v1.4.ckpt|
Anything 3.0|anything_v3.0.ckpt|
DreamLike Photo 2.0|dreamlike_photoreal_v2.0.safetensors|
DreamLike 1.0|dreamlike10.ckpt|
FAD 0|FAD_v0.safetensors|
Imagination|imagination_mix.ckpt|
Liberty|liberty_main.safetensors|
Lucid|lucid_mix.ckpt|
OpenJourney|openjourney_v4.ckpt|
PFG|pfg.safetensors|
Protogen 2.2|protogen_v2.2.ckpt|
Protogen 3.4|protogen_v3.4.ckpt|
RealVision 1.2|realistic_vision_v1.2.safetensors|
RealVision 1.3|realistic_vision_v1.3.safetensors|
```
The problem is the bot shows only last line of the config instead of full list
![selector](https://user-images.githubusercontent.com/51263156/222995732-c93b6930-c5c7-4fa1-882f-99b2b464fbf3.PNG)
and when I use it in my SD Web UI console I see messages like 
`Checkpoint RealVision 1.3 not found; loading fallback dreamlike_photoreal_v2.0.safetensors [92970aa785]`
though `RealVision 1.3` is just a display name, not a name of a model, which should be `realistic_vision_v1.3.safetensors` and that model file exists and is shown that way in WEB UI. SD uses just a random model instead of missing RealVision 1.3

---

**Environment**
I use AUTOMATIC1111 Web UI from the releases package - https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases
on Windows 10 22H2
SD Web UI launch args are: `set COMMANDLINE_ARGS=--listen --hide-ui-dir-config --enable-console-prompts --enable-insecure-extension-access --api`
All model files are located in `WEBUIv1.0\webui\models\Stable-diffusion`
I run AIYA in docker using WSL 2 with
`docker run --name aiyabot --network=host --restart=always -e TOKEN=<token> -e TZ=Europe/Berlin -e URL=http://<IP:PORT> -v D:\Neural\SD\aiyabot_folders\outputs:/app/outputs -v D:\Neural\SD\aiyabot_folders\resources:/app/resources -d ghcr.io/kilvoctu/aiyabot:latest`
Also I have a bit unusual setup of models folder, instead of model files I put symlinks to the files because I use models in two different setups of SD and would like to save some space on my disk.

EDIT:
Also forgot to mention, I had to manually edit the URL for my SD install in config.toml, because by some reason the bot still tried to access 127.0.0.1.

**Comment by Kilvoctu** [comment]
Heya, I'm curious. If you strip out the file extension, does it show all 15 models? So like this :
```
display_name|model_full_name|activator_token
SD 1.5|stable_diffusion_v1.5|
SD 1.4|stable_diffusion_v1.4|
Anything 3.0|anything_v3.0|
DreamLike Photo 2.0|dreamlike_photoreal_v2.0|
DreamLike 1.0|dreamlike10|
FAD 0|FAD_v0|
Imagination|imagination_mix|
Liberty|liberty_main|
Lucid|lucid_mix|
OpenJourney|openjourney_v4|
PFG|pfg|
Protogen 2.2|protogen_v2.2|
Protogen 3.4|protogen_v3.4|
RealVision 1.2|realistic_vision_v1.2|
RealVision 1.3|realistic_vision_v1.3|
```

**Comment by Comdriver** [comment]
Yes, without extensions it works now. Have full list of the models in Discord and SD Web UI switches them correctly. Thanks!
I'm closing the issue.

**Comment by Kilvoctu** [comment]
Nice, glad it works for you. 👍
I should revise the wiki to communicate this as the preferred way to configure the models, at least until [gui project](https://github.com/users/Kilvoctu/projects/1) is done that should make setup much simpler.  

The only issue is having same filenames different extensions, but that's probably such a niche use case that it's not much concern.
