### ISSUE TITLE
aiyabot not talking to latest AUTOMATIC1111 backend

### ISSUE THREAD

**Issue by scumola** [Kilvoctu/aiyabot#140]
**Describe the bug**  
I'm using the latest AUTOMATIC1111 backend.  I'm unable to talk to the backend at all.  Models aren't populated in models.csv although the API url is the same as before and works as expected.  The only commands available in the bot are /info and /stats.  None of the other commands are even populating.

Tried running as a stand-alone script and also tried running as docker-compose.  No errors, just not working.

---

**Environment**
 - OS: Linux

**Comment by Kilvoctu** [comment]
I'm on Web UI commit `0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8` and it should be working. Even if the backend wasn't available, all slash commands should be there anyways (they would just not respond if used). It sounds like something else is the matter. I'll need more information to troubleshoot your issue.

Was this working before Web UI commit `0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8`?  
When you said the API url is the same as before and works as expected, what do you mean? Do you mean it works with other frontends (not the aiyabot)?
Are there any errors in AIYA's console log or Web UI console log?  
When you do /info, then click Models, nothing appears?
Did server host confirm the slash command permissions in server settings -> Apps -> Integrations.
Also note I disable use of AIYA in DMs (only /info and /stats can be used in DMs). She can only be used in servers.

**Comment by scumola** [comment]
I just started using the bot, so I'm not sure if it worked before the latest web ui commit.
I mean, I can get the list of models from the backend using the same url as it's always been. {url}/sdapi/v1/sd-models returns good json, so the API is running.
No errors.  Last line in the logs is the json from connecting to discord.
Models is only populated with what I manually put in models.csv.  It doesn't auto-populate.  It does pop up an empty list though.
Re: slash command permissions:
![image](https://user-images.githubusercontent.com/386016/223783457-1c38f450-9cec-43e9-aaa8-a6d136f90c17.png)
This is what I'm able to do when I hit "/":
![image](https://user-images.githubusercontent.com/386016/223783900-67beef10-03b2-49d9-9582-f7d3be9a5bfe.png)
Oh, that might be it.  I need to invite the bot to a channel, I guess.  Maybe the command thing is my fault then.

**Comment by Kilvoctu** [comment]
> Models is only populated with what I manually put in models.csv. It doesn't auto-populate.  

This is intentional. I don't want the aiyabot to automatically pull all models from Web UI.  
What does your models.csv look like?

**Comment by Kilvoctu** [comment]
I'll be closing this as it's been some time without a response. If there are further issues, feel free to follow up.
