### ISSUE TITLE
Exceeding max steps

### ISSUE THREAD

**Issue by Mark-papi** [Kilvoctu/aiyabot#150]
Exceeding max steps
---
is there a way to exceed the max steps, lets say i want to do 73 steps, can i edit some line of code to get the desirable result ?

Thanks for any answer regarding my problem!

**Environment**
 - OS: [e.g. Windows / Linux]
Windows

**Comment by Kilvoctu** [comment]
Heya, please check the section here on the wiki in regards to max steps
https://github.com/Kilvoctu/aiyabot/wiki/settings-command#settings

**Comment by Mark-papi** [comment]
> Heya, please check the section here on the wiki in regards to max steps https://github.com/Kilvoctu/aiyabot/wiki/settings-command#settings
