### ISSUE TITLE
Discord 403 Forbidden, Missing Access 

### ISSUE THREAD

**Issue by fiveseven808** [Kilvoctu/aiyabot#151]
**Describe the bug**  

I think I have everything setup, combining both the main README.md and the wiki, I've created a discord bot and linked it to my server and it can successfully receive commands. It successfully sends the commands to my stable diffusion install, and a generated image shows up under the /output directory, but.... It breaks when trying to send the image to discord it seems?

`Request -- N****#0001 -- Prompt: test -- Using model:
Saved image: outputs/1679284852-1514181095-test-1.png
[2023-03-19 18:00:56] ERROR: Task exception was never retrieved
future: <Task finished name='Task-51' coro=<Messageable.send() done, defined at C:\VRC\aiyabot\venv\lib\site-packages\discord\abc.py:1390> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\VRC\aiyabot\venv\lib\site-packages\discord\abc.py", line 1572, in send
    data = await state.http.send_files(
  File "C:\VRC\aiyabot\venv\lib\site-packages\discord\http.py", line 365, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access `

The bot seems to be able to make commands and send messages just fine... so I'm a little confused as to why it says missing access... 

I'm sure I must've screwed something up but I'm not sure what.
---

**Environment**
 - OS: Windows 10

**Comment by Kilvoctu** [comment]
Heya, make sure the `applications.commands` scope is enabled in your bot's oauth2 settings 
![image](https://user-images.githubusercontent.com/2993060/226257498-75736d6f-79ee-43b4-a4b6-819cf1d5cc47.png)

You might have to kick and reinvite her for it to take effect.

**Comment by fiveseven808** [comment]
Ahh... You can close this. I was testing in a private channel in my server and it wasn't working right, but I tested in a more public channel and it seems to have worked! Thank you for such a quick response. 

What I don't understand is that I'm able to send commands to the bot in channels it doesn't appear to be in? It's not in the users list for that channel... but it seems to be able to respond to commands there...

**Comment by Kilvoctu** [comment]
Glad it's working for you 👍 

If you're server admin, you're going to see and use the commands everywhere regardless of settings. Otherwise, slash command permissions are set through Apps -> integrations. The [Discord doc is here](https://discord.com/blog/slash-commands-permissions-discord-apps-bots) (scroll about halfway down the page).
