### ISSUE TITLE
max_size wont go above 1024

### ISSUE THREAD

**Issue by fiveseven808** [Kilvoctu/aiyabot#159]
I'm trying to set max_size to 2048 as that's the largest in the webui, and I need a higher resolution for my manual "hires fix" via img2img upscaling. 

When I set config.toml's max_size to 2048, nothing in the bot changes, and I am unable to put a value higher than 1024, it complains about an invalid value.

**Comment by Kilvoctu** [comment]
Thanks for the bug report. This is indeed a bug 🤔 but it's not completely AIYA's fault lol
The reason is Discord has a limit of 25 choices per option. Setting the max size to 2048 creates 30 choices (I counted), so Discord will not allow it.  
I'll need to write an exception to get around this limitation.

**Comment by Kilvoctu** [comment]
Heya, please pull the latest update https://github.com/Kilvoctu/aiyabot/commit/074d54e1bfc3f23c7d1f671eeaaa50cf599d7627 and see if it works for you.

Keep in mind Discord's 25 choices limit also applies to what's visible in the selection window (only 192 to 1728 will be visible). You'll need to type the number to search for values greater than that. 
![image](https://user-images.githubusercontent.com/2993060/228485148-a239b177-ea3f-4df8-a8bd-b46a1dc11b49.png)

**Comment by Kilvoctu** [comment]
> There's an issue where the edit button no longer works.

I had to update the 🖋️ too to support large sizes. Please git pull the new update. It should work in theory, but I'm not able to test it as my PC literally cannot generate images that large. See if it works for you.

> 
> Unrelated, but auto1111 repo seems to have some sort of weird vram memory leak?

Please submit a new issue if this happens again.

**Comment by fiveseven808** [comment]
The edit button works fine now!
However, the clipboard button no longer works for me. I get the following error:

> I may have been restarted. This button no longer works.
> You can get the image info from the context menu or /identify.

**Comment by Kilvoctu** [comment]
Please give the console log error.

**Comment by fiveseven808** [comment]
> The image info command broke: list index out of range
> The clipboard button broke: 'NoneType' object has no attribute 'respond'

**Comment by Kilvoctu** [comment]
As AIYA mentions on the end user message, buttons don't work after being restarted. If you want to id the image, use the other options.

**Comment by fiveseven808** [comment]
No, this happens immediately after the image is generated. The bot has not been restarted.

**Comment by Kilvoctu** [comment]
Does using the context menu option work?

**Comment by fiveseven808** [comment]
I did not try it until now, but I get the following error when trying it:
`The image information is empty or unreadable!`

**Comment by Kilvoctu** [comment]
After looking into it further, it appears to be something Discord did/broke recently. I created #161

Since it's not related to max_size issue, I will be closing this issue as resolved.
