### ISSUE TITLE
Missing permissions

### ISSUE THREAD

**Issue by XiPoWnZX** [Kilvoctu/aiyabot#182]
**Describe the bug**  
I just tried to create a picture with the bot and got an error, it was working fine when i installed it like **2 weeks** ago, then it stopped sending the pictures to the discord when i start it back yesterday. I have tried to look what could do that and didnt find.

---

**Environment**
 - OS: Windows 10 Pro
---

**Console logs**  
Saved image: outputs/1684885121-1187717594-1.png
[2023-05-23 19:41:40] ERROR: Task exception was never retrieved
future: <Task finished name='Task-27' coro=<Messageable.send() done, defined at G:\DiscBot\aiyabot\venv\lib\site-packages\discord\abc.py:1390> exception=Forbidden('403 Forbidden (error code: 50013): Missing Permissions')>
Traceback (most recent call last):
  File "G:\DiscBot\aiyabot\venv\lib\site-packages\discord\abc.py", line 1572, in send
    data = await state.http.send_files(
  File "G:\DiscBot\aiyabot\venv\lib\site-packages\discord\http.py", line 365, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

**Comment by Kilvoctu** [comment]
> I have tried to look what could do that and didnt find.

Heya I probably need some more information on what you've tried.  
In any case this is a Discord permissions issue, not a bug with AIYA. I can't do anything when it comes to how you set up your server permissions 👀.  

Please ensure your deployment has the necessary Discord permissions. If all else fails, you could reinvite your bot with the correct scopes/permissions. https://github.com/Kilvoctu/aiyabot/wiki/Setting-up-a-Discord-bot  
From my experience, `bot` and `application.commands` was enough, but you could add more just to get it working https://stackoverflow.com/questions/56822419/discord-errors-forbidden-403-forbidden-error-code-50013-missing-permissions

**Comment by XiPoWnZX** [comment]
Thats what i found weird i didnt change anything from the last time it was working, its in same channel and same permission :/ will try some differents things and keep updated

**Comment by XiPoWnZX** [comment]
Was 100% a permission that have changed i dont know how as im alone in this discord xD Thanks for pointing out :)

**Comment by Kilvoctu** [comment]
No problem, glad you got it resolved 👍
