### ISSUE TITLE
Prompts with characters that can't be stored in filenames fail to generate

### ISSUE THREAD

**Issue by philpax** [Kilvoctu/aiyabot#21]
The raw prompt is used for output filenames, which causes issues when those characters can't be represented on the host's filesystem:
![image](https://user-images.githubusercontent.com/707827/198781792-e55d382b-3f58-4dcb-860a-8969ed535b0f.png)
![image](https://user-images.githubusercontent.com/707827/198781838-60181cfd-ce12-4899-aff4-f07697446789.png)

I'd suggest slugify-ing them or otherwise sanitising them.

**Comment by Kilvoctu** [comment]
Hi, I think I got it with 47014b64e8cf9d97ee13ced59c02a4877e8d67a4. Can you confirm if it works for you?

For me, I tried prompt
![image](https://user-images.githubusercontent.com/2993060/198858740-fd33b79e-bbbe-4506-8745-aea352f01f51.png)
and got this file
![image](https://user-images.githubusercontent.com/2993060/198858732-26819cfe-82dc-4b97-a3fb-0d5f06fc6498.png)

**Comment by philpax** [comment]
Can confirm it works now! Thank you very much 👌
