### ISSUE TITLE
A1111 v1.6.0 - Samplers > 25

### ISSUE THREAD

**Issue by wizz13150** [Kilvoctu/aiyabot#212]
Hey,

I think it's legit to open an Issue for this, for an official and proper fix.

((: 

### Discussed in https://github.com/Kilvoctu/aiyabot/discussions/211

<div type='discussions-op-text'>

<sup>Originally posted by **wizz13150** September  4, 2023</sup>
Hey, 

there is too many Samplers in the last update.
Causing a 'choices >25' error at launch of the bot.

Not sure which samplers should be ignored, so i just added this in `settings.py` :

![image](https://github.com/Kilvoctu/aiyabot/assets/22177081/557d3e4b-6feb-487e-a20c-8f5ae7680e41)

An existing bot will be 'fine', But this error also prevents the synchronization of commands, so it's **blocking** for fresh installations or modifications.
Annoying.
Maybe this should be in Issue 🤔

Cheers ! 🥂
</div>

**Comment by wizz13150** [comment]
Log DEBUG level for discord :

blablabla

{"name":"sampler","description":"Set default sampler for the channel","type":3,"required":false,_**"choices":[{"name":"DPM++ 2M Karras","value":"DPM++ 2M Karras"},{"name":"DPM++ SDE Karras","value":"DPM++ SDE Karras"},{"name":"DPM++ 2M SDE Exponential","value":"DPM++ 2M SDE Exponential"},{"name":"DPM++ 2M SDE Karras","value":"DPM++ 2M SDE Karras"},{"name":"Euler a","value":"Euler a"},{"name":"Euler","value":"Euler"},{"name":"LMS","value":"LMS"},{"name":"Heun","value":"Heun"},{"name":"DPM2","value":"DPM2"},{"name":"DPM2 a","value":"DPM2 a"},{"name":"DPM++ 2S a","value":"DPM++ 2S a"},{"name":"DPM++ 2M","value":"DPM++ 2M"},{"name":"DPM++ SDE","value":"DPM++ SDE"},{"name":"DPM++ 2M SDE","value":"DPM++ 2M SDE"},{"name":"DPM++ 2M SDE Heun","value":"DPM++ 2M SDE Heun"},{"name":"DPM++ 2M SDE Heun Karras","value":"DPM++ 2M SDE Heun Karras"},{"name":"DPM++ 2M SDE Heun Exponential","value":"DPM++ 2M SDE Heun Exponential"},{"name":"DPM++ 3M SDE","value":"DPM++ 3M SDE"},{"name":"DPM++ 3M SDE Karras","value":"DPM++ 3M SDE Karras"},{"name":"DPM++ 3M SDE Exponential","value":"DPM++ 3M SDE Exponential"},{"name":"DPM fast","value":"DPM fast"},{"name":"DPM adaptive","value":"DPM adaptive"},{"name":"LMS Karras","value":"LMS Karras"},{"name":"DPM2 Karras","value":"DPM2 Karras"},{"name":"DPM2 a Karras","value":"DPM2 a Karras"},{"name":"DPM++ 2S a Karras","value":"DPM++ 2S a Karras"},{"name":"Restart","value":"Restart"},{"name":"DDIM","value":"DDIM"},{"name":"PLMS","value":"PLMS"},{"name":"UniPC","value":"UniPC"}],**_

blablabla

( 30 samplers, i did count lol )

**Comment by solareon** [comment]
This is a discord api limitation. You are only allowed to present up to 25 options in a menu, 25 buttons, 25 attachments, etc. Anything more requires pagination in some fashion.

**Comment by wizz13150** [comment]
Yeah, but we're talking about a fresh installation of the bot, not allowing to sync commands.

The bot is broken atm. ((:
