### ISSUE TITLE
Malware warnings

### ISSUE THREAD

**Issue by DavidSchobl** [Kilvoctu/aiyabot#233]
**Describe the bug**  
Avast is giving me two malware warnings: IDP.generic and IDP.HELU.PSE40, also meanwhile, it is opening som window with "pick the source of the video".

---

**Environment**
 - Windows

---

**Console logs**  
No connected console logs.

**Comment by sebaxakerhtc** [comment]
Looks like only your computer is affected. Tested on a clean Windows installation

**Comment by Kilvoctu** [comment]
Heya, sounds like a false positive. I don't use Avast, but it probably gives some scan results. Will need more information than what is given here.

**Comment by DavidSchobl** [comment]
Now it works fine.

**Comment by DavidSchobl** [comment]
Probably false positive.
