### ISSUE TITLE
Generations fail to save to output

### ISSUE THREAD

**Issue by Xythrr** [Kilvoctu/aiyabot#238]
**Describe the bug**  
The bot fails to save the generated image to the output folder, around thirty to fifty percent of the time.

---

**Environment**
Windows 11, AMD

---

**Console logs**  
No error messages, just doesn't have "Saved image: outputs/xxxxx.png" occasionally.

**Comment by Gecktendo** [comment]
I think somewhere the output is returning false:
![Screenshot_20240302-001458](https://github.com/Kilvoctu/aiyabot/assets/125915576/4a1b6da3-576a-4308-a7a1-be286ad86519)

**Comment by JoshBaldwin101** [comment]
I'm getting this also when upscaling.

**Comment by FoxxMD** [comment]
I'm looking into it to see if its related to [my PR](https://github.com/Kilvoctu/aiyabot/commit/6f4f83201f374f3bc1b16724f24978e479528166)...
