### ISSUE TITLE
Clicking on the "X" button doesn't work.

### ISSUE THREAD

**Issue by Gecktendo** [Kilvoctu/aiyabot#254]
**Describe the bug**  
Title. Clicking on the x button returns the "I may have been restarted" message instead of deleting the image.

---

**Environment**
 Windows

---

**Console logs**  
I may have been restarted. This button no longer works.
You can react with ❌ to delete the image.

**Comment by Gecktendo** [comment]
Looks like a reset fixed it. Nevermind.

**Comment by Gecktendo** [comment]
Looks like the problem is back. It works for the first couple of uses, but if you upscale or use the same seed it breaks again.

**Comment by Kilvoctu** [comment]
Heya, it should be fixed now with 3b96cf691515f5f73803367d5ed6ea6eb0bbf2c7. Bug was caused because I overlooked some stuff when merging my PR #252
