### ISSUE TITLE
Deleting old runs will fail if a newer run has been started.

### ISSUE THREAD

**Issue by Gecktendo** [Kilvoctu/aiyabot#258]
**Describe the bug**  
Clicking on the "X" fails if you try to do this with an older submission. The bot has not been restarted but it fails anyway.

---

**Environment**
 - Windows 11

---

**Console logs**  
I may have been restarted. This button no longer works.
You can react with ❌ to delete the image.

**Comment by Gecktendo** [comment]
Looks like this fails with the newest run as well. Not sure the cause but something is glitching out.

**Comment by Kilvoctu** [comment]
Heya, not really sure what you mean by "runs" and "submissions". I don't understand what this vocabulary means in context with the aiyabot, but I think I fixed what I assume you're talking about.
