### ISSUE TITLE
Problem:     for d in range(len(old_config["dependencies"])): KeyError: 'dependencies'

### ISSUE THREAD

**Issue by Darkflo264** [Kilvoctu/aiyabot#31]
Hello!

I would love to try and use your bot but sadly i am running into a error when trying to launch the launch.bat

I think the requirements are already satisfied, the --api parameter is added, the SD-Web-UI is running and accessable by /config and /api
Bot token and credentials are present in the .env file.

Maybe someone can fix or help me what the problem is (i´ll copy the whole bunch in here):

`D:\AI-Painting\06_aiyabot>"D:\AI-Painting\06_aiyabot\venv\Scripts\Python.exe" launch.py
Requirement already satisfied: py-cord in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from -r requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: python-dotenv in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from -r requirements.txt (line 2)) (0.21.0)
Requirement already satisfied: requests in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from -r requirements.txt (line 3)) (2.28.1)
Requirement already satisfied: Pillow in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from -r requirements.txt (line 4)) (9.3.0)
Requirement already satisfied: aiohttp<3.9.0,>=3.6.0 in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from py-cord->-r requirements.txt (line 1)) (3.8.3)
Requirement already satisfied: charset-normalizer<3,>=2 in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from requests->-r requirements.txt (line 3)) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from requests->-r requirements.txt (line 3)) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from requests->-r requirements.txt (line 3)) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from requests->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: attrs>=17.3.0 in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (22.1.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (6.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: aiosignal>=1.1.2 in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\ai-painting\06_aiyabot\venv\lib\site-packages (from aiohttp<3.9.0,>=3.6.0->py-cord->-r requirements.txt (line 1)) (1.8.1)

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: D:\AI-Painting\06_aiyabot\venv\Scripts\python.exe -m pip install --upgrade pip
['aiohttp', 'aiosignal', 'async-timeout', 'attrs', 'certifi', 'charset-normalizer', 'frozenlist', 'idna', 'multidict', 'Pillow', 'py-cord', 'python-dotenv', 'requests', 'urllib3', 'yarl'] installed
[2022-11-02 09:55:27] WARNING: PyNaCl is not installed, voice will NOT be supported
Using URL: http://127.0.0.1:7860
Using outputs directory: outputs
Traceback (most recent call last):
  File "D:\AI-Painting\06_aiyabot\launch.py", line 12, in <module>
    import aiya
  File "D:\AI-Painting\06_aiyabot\aiya.py", line 20, in <module>
    settings.old_api_check()
  File "D:\AI-Painting\06_aiyabot\core\settings.py", line 124, in old_api_check
    for d in range(len(old_config["dependencies"])):
KeyError: 'dependencies'`

**Comment by Kilvoctu** [comment]
You mentioned that you're using credentials, so you're connecting through --share and --gradio-auth ? I did forget to test for that 🤦‍♀️Let me look into it.

**Comment by Darkflo264** [comment]
Thank you for your response!

Exactely, I am using --share and --gradio-auth.

**Comment by Kilvoctu** [comment]
Sorry about that, since I use --listen exclusively, I tend to forgettesting for --gradio-auth
I pushed an update that should fix it. Can you give it a try?

Also, I knew your name sounded familiar. You use dalebot too 😄. That bot and its developer inspired me a lot.

**Comment by Kilvoctu** [comment]
Haven't been any reply, and I'm fairly certain I fixed this particular issue.
I'm closing this issue. If there's anything else wrong, you may open a new issue.
