### ISSUE TITLE
Model switching is stuck on what the webui is set on

### ISSUE THREAD

**Issue by cadaeix** [Kilvoctu/aiyabot#32]
@Philpax was trying to get the model switching working, but it seems whatever the webui is set to overrides the model selection in the discord bot!

How to replicate: Set one model in the webui, try to prompt with another model with the discord bot

**Comment by Kilvoctu** [comment]
Yeah, setting up the models is clunky and has a lot of room for error; I'm not sure of a better way to set it up. I need to think of some more ways to streamline the process. I'll go through a few troubleshooting steps that I can think of, and hopefully one of them is the root of the issue

When you launch aiya, in the console she will confirm the fn_index. Do you see that line; it looks like this
![image](https://user-images.githubusercontent.com/2993060/199583971-66a2dade-d095-4713-9669-20b3f5e6fb24.png)
If she doesn't see it, then the `model_fn_index` is defaulted to 0 and the model payload will fail later on

-----
Whenever you prompt with the other model, it shows the display name you set for it, right? So like on mine it shows 
![image](https://user-images.githubusercontent.com/2993060/199580036-473aa065-d018-496a-b016-2c090dc45b72.png)
and for me, that corresponds to this in the web ui
![image](https://user-images.githubusercontent.com/2993060/199580306-968a2ce5-c1d5-4e78-b8df-ddda63af273f.png)
This is how I have my csv. The name has to match what's in web ui
![image](https://user-images.githubusercontent.com/2993060/199581541-fb8696c2-ba9a-4e30-aab7-36531e883b97.png)

-----
In the code itself, as long as any option is selected for "data_model" it should attempt to swap the model
https://github.com/Kilvoctu/aiyabot/blob/8b8726e81dc80723e42e761605d343bc01dbbace/core/stablecog.py#L163-L168

Is any of these getting me close? The only other reason I can think of, kinda related to above, is if web ui doesn't recognize the name you're sending to it and goes to a fallback. It'll show in your web ui console, like this (here this failed  as I didn't include ".ckpt")
![image](https://user-images.githubusercontent.com/2993060/199586134-930e0d23-9ff0-44f3-b387-50d7bd5e1136.png)

**Comment by philpax** [comment]
Apologies - I was planning on filing this myself but I had to go to work. At first, I thought it was because I didn't have the hash in the checkpoint, so I fixed that:
```
display_name|model_full_name
classic-animation|classic-animation.ckpt [be7ddafc]
sd-v1-4|sd-v1-4.ckpt [7460a6fa]
sd-v1-5-inpainting|sd-v1-5-inpainting.ckpt [3e16efc8]
sd-v1-5-pruned-emaonly|sd-v1-5-pruned-emaonly.ckpt [81761151]
trinart2_step95000|trinart2_step95000.ckpt [cf0bd941]
wd-v1-3-float16|wd-v1-3-float16.ckpt [84692140]
```
(extracted directly from the web UI using `copy(Array.from(temp0.querySelectorAll('option')).map(a => a.innerText).map(a => [a.split('.')[0], a].join('|')).join('\n'))`, where `temp0` is the dropdown)

Unfortunately, this doesn't seem to work - my aiya logs show:
```
The fn_index for the model is 212!
...
/draw prompt:a handsome test steps:30 height:512 width:512 guidance_scale:7.0 sampler:Euler a seed:3850466091 count:2 data_model:sd-v1-5-pruned-emaonly
Saved image: outputs\1667422306-3850466091-a handsome test-0.png
Saved image: outputs\1667422306-3850466091-a handsome test-1.png
Request -- Philpax#0001 -- Prompt: a handsome test
/draw prompt:a handsome test steps:30 height:512 width:512 guidance_scale:7.0 sampler:Euler a seed:2914185350 count:2 data_model:sd-v1-4
Saved image: outputs\1667422356-2914185350-a handsome test-0.png
Saved image: outputs\1667422356-2914185350-a handsome test-1.png
```
and my a1111 logs show:
```
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.98it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  8.33it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.95it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.78it/s]
```
(i.e. it made no effort to switch)

Switching in the UI _does_ work, however:
```
Loading weights [81761151] from stable-diffusion-webui\models\Stable-diffusion\sd-v1-5-pruned-emaonly.ckpt
Global Step: 840000
Applying cross attention optimization (Doggettx).
Weights loaded.
```

This is with the latest aiyabot and a1111 (just pulled now). And yep, all of the models show up in the Discord command and in the copy-output, so I'm pretty sure it's an issue with the switching... might be easier to fix, I'll have a look at it over dinner

**Comment by Kilvoctu** [comment]
Thanks for the info. That does all check out.
It's probably some hole in the code logic. It was a pretty big update, I was expecting some bugs 😅
I'll try to recreate the issue and look at it too. Conveniently, I have all those models downloaded too

**Comment by philpax** [comment]
https://github.com/Kilvoctu/aiyabot/pull/35 hehe

**Comment by Kilvoctu** [comment]
It was a hole in my testing 😅

Thanks for the report and the fix, you all 👍👍
