### ISSUE TITLE
IndexError on line 323 in dream. Image doesn't get posted to Discord

### ISSUE THREAD

**Issue by katethefox** [Kilvoctu/aiyabot#34]
I am running into an issue in the latest version of Aiyabot.
After the image is generated by StableDiffusion, I get an error from Aiyabot and it doesn't post it to discord.
This has worked before on an earlier version of Aiyabot.. not sure what went wrong.
I am using the recommended git version of AUTOMATIC1111 that is mentioned in the Readme.
I am getting the following error 

`
      
    
    /draw prompt:test steps:30 height:512 width:512 guidance_scale:7.0 sampler:Euler a seed:2987020433 count:1
    Traceback (most recent call last):
    
      File "C:\AI-ART\aiyabot\aiyabot\core\stablecog.py", line 323, in dream
    
        image = Image.open(io.BytesIO(base64.b64decode(image_base64.split(",",1)[1])))
    
    IndexError: list index out of range
    
    Request -- Kate#xxxx  -- Prompt: test
    
    /draw prompt:test steps:30 height:512 width:512 guidance_scale:7.0 sampler:Euler a seed:373217648 count:1
    
    Traceback (most recent call last):
    
      File "C:\AI-ART\aiyabot\aiyabot\core\stablecog.py", line 323, in dream
    
        image = Image.open(io.BytesIO(base64.b64decode(image_base64.split(",",1)[1])))
    
    IndexError: list index out of range

`

**Comment by Eidenz** [comment]
linked to !33

**Comment by MotorMan** [comment]
i had this issue yesterday, and was able to fix it by taking the original line, and removing the split function.
resulting in the line being:
image = Image.open(io.BytesIO(base64.b64decode(image_base64)))

i don't know why the split was having problems or why it was needed, but somehow, removing it fixed it. i'm not familiar with python yet, so it's still magic to me. lol 
i did try the fix in the #33 PR, but it just resulted in:
    image = Image.open(io.BytesIO(base64.b64decode(image_base64(",",1)[0])))
TypeError: 'str' object is not callable

hope this helps. also i'm still on the webui version that was listed yesterday.

**Comment by Eidenz** [comment]
> i had this issue yesterday, and was able to fix it by taking the original line, and removing the split function. resulting in the line being: image = Image.open(io.BytesIO(base64.b64decode(image_base64)))
> 
> i don't know why the split was having problems or why it was needed, but somehow, removing it fixed it. i'm not familiar with python yet, so it's still magic to me. lol i did try the fix in the #33 PR, but it just resulted in: image = Image.open(io.BytesIO(base64.b64decode(image_base64(",",1)[0]))) TypeError: 'str' object is not callable
> 
> hope this helps. also i'm still on the webui version that was listed yesterday.

If you copy pasted correctly, you forgot the `split` in your line (which explains any error):

`image = Image.open(io.BytesIO(base64.b64decode(image_base64(",",1)[0])))`
should be
`image = Image.open(io.BytesIO(base64.b64decode(image_base64.split(",",1)[0])))`

**Comment by MotorMan** [comment]
> 

ha, good one. i totally missed that!

**Comment by Eidenz** [comment]
I was talking about this part:
> i did try the fix in the https://github.com/Kilvoctu/aiyabot/pull/33 PR, but it just resulted in:
> image = Image.open(io.BytesIO(base64.b64decode(image_base64(",",1)[0])))
> TypeError: 'str' object is not callable

**Comment by Kilvoctu** [comment]
#33 is merged, so it should fix this issue for now. Thanks @Eidenz . I'd love it if web ui repo would stop randomly changing the api response 😂.
Looking at the response body of web ui, the split shouldn't be necessary, but if this is faster and still works, then 👍

**Comment by katethefox** [comment]
> #33 is merged, so it should fix this issue for now. Thanks @Eidenz . I'd love it if web ui repo would stop randomly changing the api response 😂. Looking at the response body of web ui, the split shouldn't be necessary, but if this is faster and still works, then 👍

Thank you so much for helping resolve this!
