### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by super3** [Kilvoctu/aiyabot#38]
Could you include a bash script in addition to the .bat so this can be easily run on a Linux machine?

**Comment by Kilvoctu** [comment]
I don't have a Linux environment to work with. I'll see if I can get some help on this request.

**Comment by super3** [comment]
@Kilvoctu I can give you access to a Linux environment. What is the best way to contact you directly?

**Comment by super3** [comment]
@Kilvoctu Actually it works just fine if you run `launch.py` by itself.

**Comment by Kilvoctu** [comment]
I was with a friend who is on Linux, and we worked together to get a simple solution for Linux users.
launch.sh should work the same as well.

**Comment by super3** [comment]
@Kilvoctu Awesome. I noticed that on Linux it outputs in images in the repo directory instead of the `/output` directory.

**Comment by Kilvoctu** [comment]
I think it's because on Linux (I was told), directories use forward slashes? My code explicitly uses backslashes, I'll look at it; should be simple I think
