### ISSUE TITLE
user failed to send instructions to the bot on the mobile phone

### ISSUE THREAD

**Issue by sheququan** [Kilvoctu/aiyabot#43]
Please help my bot, he works fine on PC side but not on mobile client side

![image](https://user-images.githubusercontent.com/117585069/200223266-cd889e2e-75ef-4ecd-94d5-f7079973fff7.png)

**Comment by Kilvoctu** [comment]
I'm not sure why that is. AIYA works on mobile for my friends and me. For me, mobile is the primary usage.
What mobile device is that? Can you provide the console log for when the interaction fails? Do all the commands fail or just /draw?

**Comment by Kilvoctu** [comment]
I'll be closing this as there's been no reply. If you still need help, feel free to re-open.
