### ISSUE TITLE
Google Colaboratory support?

### ISSUE THREAD

**Issue by matroxI** [Kilvoctu/aiyabot#50]
Hello, can you please make a google colab with your repository? I tried to make it, but I lack the knowledge of python. Yesterday I updated python on colab and even managed to run launch.py and aiya.py at the same time, but nothing worked. Today I couldn't even do that. Please, I beg you, this will be very useful for people with an amd graphics card like me, or people who don't have a powerful enough graphics card to run stable diffusion. Thanks in advance

**Comment by matroxI** [comment]
![image](https://user-images.githubusercontent.com/111098250/201358887-7b703fa3-5b80-455e-8277-fbd00deeb730.png)
The farthest point I got to is this error

Uh oh, stats.txt missing. Creating a new one.
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/aiyabot/aiya.py", line 20, in <module>
    settings.files_check()
  File "/content/stable-diffusion-webui/aiyabot/core/settings.py", line 88, in files_check
    with open('resources/stats.txt', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'resources/stats.txt'

**Comment by Kilvoctu** [comment]
Sure, I'll look into finding some process that work for Google Colab.  

I've heard of people using Colab before, but I don't know anything about it, so I'll have to give it a try myself. Are all those project files on your PC or a Google server?
Also ironic is I, too, lack knowledge in Python 😂; no Python knowledge prior to this project. It took me a week to figure out how add Discord button into the generated image output https://github.com/Kilvoctu/aiyabot/commit/9154a899d33f9008b141661984afde561d32b0b5 (and it doesn't do anything yet).

Anyway, in your screenshot, it looks like you have A1111 repo running and aiya does connect to it, but she is failing at the very next step. The aiya initialization is a server check, files check, then discord guilds check. "stats.txt" is the first file to check, and as seen in the log she tries to create it with https://github.com/Kilvoctu/aiyabot/blob/1ec49104e8a6090ef2a646bed4526bf9d27ebb65/core/settings.py#L88-L89
While this works on Windows (and Linux, I guess) to "open" a non-existent file to create it, it seems Colab doesn't like it for some reason. There's a few `with open` lines in the initialization; stats.txt, models.csv, and a json file for each Discord guild aiya is in.

Right now I'm trying to finish off issue #19. Afterward, I'll focus on seeing what I can do for Google Colab, but I'll probably dabble in it at the same time.

**Comment by matroxI** [comment]
Thank you very much, I really appreciate it. Google colab is an environment that runs on Google servers. In this environment, you are given approximately 16GB of video memory and 80GB of space. The whole environment is based on Linux and jupyter notebooks, so the code from Jupyter will work for you in the colab. After about 12 hours, you are disconnected from the environment and all files are deleted (you can still use it, but without a video card). Below is some code that might help a little.
```
import sys

#The only way I found to update python so all other modules don't break. A newer python is needed for one of the discord libraries. By default, the colab is set to python 3.7.something

!python --version
!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh
!chmod +x mini.sh
!bash ./mini.sh -b -f -p /usr/local
!conda install -q -y jupyter
!conda install -q -y google-colab -c conda-forge
!python -m ipykernel install --name "py39" --user
!python --version
print(sys.version)

#the text about python vesion is strangely updating, sometimes it immediately writes the current version, sometimes it writes the old one.

#!sh /content/stable-diffusion-webui/aiyabot/launch.sh is not working and not installing anything, (maybe because it creates a local environment?) so we install packages manually.

!pip install py-cord
!pip install discord
!pip install python-dotenv
%cd /content/stable-diffusion-webui
!git clone https://github.com/Kilvoctu/aiyabot


!python /content/stable-diffusion-webui/aiyabot/aiya.py & python /content/stable-diffusion-webui/launch.py --listen --api --share --gradio-auth e:e

#Since we are not at the computer, but in the cloud, --share is required
```

**Comment by matroxI** [comment]
Ok, I just figured out why stats.txt can't be read. This is all because the relative path breaks when running two files. The relative path only works for the path that was chosen by location in the bash command. Thus, the error that I threw off above occurs because the readable path of the aiya.py file is considered to be /content/stable-diffusion-webui/resources/stats.txt

![image](https://user-images.githubusercontent.com/111098250/201495500-e4af3c3c-1465-4392-80e0-923b0af2233c.png)

Here is a screenshot from the other side. The -m pip install -r requirements_versions.txt command tries to be read as: -m pip install -r /content/aiyabot/requirements_versions.txt There is no such file, so an error is thrown. The solutions I see: Either rewrite the bot files so that they have absolute paths, or merge all files from the aiyabot folder into the stable-diffusion-webui folder

If anything works out, I'll post it.

**Comment by Kilvoctu** [comment]
Are you running your own colab of Web UI, or using one of the ones in https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Online-Services. I'm still trying to get it set up 😅

**Comment by matroxI** [comment]
> Are you running your own colab of Web UI, or using one of the ones in https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Online-Services. I'm still trying to get it set up 😅

Yes, I use my non-public colab. Here's the part I'm scratching my head over. https://colab.research.google.com/drive/1RNvnsXqMYcNUZw-ammHgW5trHbIdhFs2?usp=sharing


Now the latest error is 
![image](https://user-images.githubusercontent.com/111098250/201496950-816c90b0-ef23-4b68-8901-723fa79285dc.png)

**Comment by Kilvoctu** [comment]
What that section of the code is doing is it's pulling the config from the web ui at {url}/config. That error means that for some reason, it couldn't access the web ui. A similar issue was reported in #31. 

I have a log in check in that section at https://github.com/Kilvoctu/aiyabot/blob/d362fbcc16b7b3d0e24199940b44d6cd6b58151a/core/settings.py#L177-L189 
which should ensure user is connected to web ui in order to pull the config. What it does is it looks at the .env file for the URL, and USER and PASS if those exist, and uses those to connect to web ui (it'll use local host if URL doesn't exist in .env)

I have another log in check earlier in the code at https://github.com/Kilvoctu/aiyabot/blob/d362fbcc16b7b3d0e24199940b44d6cd6b58151a/core/settings.py#L131-L132
This one doesn't give an error if it fails. I am wondering if your bot is able to authenticate with web ui. You are using, `--share` right?

What I was trying to figure out at the moment actually, is a sensible way to set up the .env file for colab (in addition to just getting it working)

**Comment by matroxI** [comment]
> This one doesn't give an error if it fails. I am wondering if your bot is able to authenticate with web ui. You are using, `--share` right?

Yes, I literally threw you a colab in which everything that I do happens. webui will be installed, modules will be updated, bot files will be merged with webui files. So if you run it, you will get the same result.

> What I was trying to figure out at the moment actually, is a sensible way to set up the .env file for colab (in addition to just getting it working)

Just make an .env on your computer and upload it to the desired file path. For some reason the .env becomes a hidden file, so you have to click on that icon to see it.

![image](https://user-images.githubusercontent.com/111098250/201497817-450c41fd-52b6-41e9-a54d-9ba515cb1a61.png)

**Comment by Kilvoctu** [comment]
> Yes, I literally threw you a colab in which everything that I do happens. webui will be installed, modules will be updated, bot files will be merged with webui files. So if you run it, you will get the same result.

Sorry, I'm not very bright 😢This project exists from determination and grinding, rather than any technical skill. While the collab code you provided works, I'm trying to mount it onto a colab of Web UI as mentioned, so we could be looking at the same thing. Right now I don't have a web ui colab working.
![image](https://user-images.githubusercontent.com/2993060/201498395-8e9fd60a-66f8-4842-a4b5-ef14e795e346.png)

**Comment by matroxI** [comment]
![image](https://user-images.githubusercontent.com/111098250/201498969-e6234c0d-4db7-4633-8e11-72e67bf4f6d0.png)


Are you sure you opened that colab? You don't even have a folder with Web UI in your screenshot. Just alternately you need to click on the play on the top cell, and then on the bottom. I logged in with a different account, everything was set up as it should.

![image](https://user-images.githubusercontent.com/111098250/201498860-e7949183-bdc5-46fa-92bd-97cfce8b7ef8.png)

**Comment by matroxI** [comment]
I'm going to bed now, it's 1:45 in my country right now, if you want, we can talk later in the discord, because it seems to me there is some kind of misunderstanding

**Comment by matroxI** [comment]
![image](https://user-images.githubusercontent.com/111098250/201515648-e1b26ce2-92cc-4c42-b630-e1e0e24fc561.png)
![image](https://user-images.githubusercontent.com/111098250/201515662-eaaa57e5-1dd3-41fe-bc3c-6a769cfd60e4.png)
I just ran the colab today, ran the first cell, then the second, after the second cell gave an error, I put the .env in the stable-diffusion-webui folder and ran the second cell again and it worked.

**Comment by matroxI** [comment]
And finally. Fully working colab:


https://colab.research.google.com/drive/1RNvnsXqMYcNUZw-ammHgW5trHbIdhFs2X

**Comment by matroxI** [comment]
And finally. Fully working colab:

https://colab.research.google.com/drive/1RNvnsXqMYcNUZw-ammHgW5trHbIdhFs2?usp=sharing

**Comment by Kilvoctu** [comment]
Cool!, Nice to see you got it working out for you. If you want, I can add it to documentation so other people can run on Colab

**Comment by matroxI** [comment]
> Cool!, Nice to see you got it working out for you. If you want, I can add it to documentation so other people can run on Colab

Yes, that would be nice, add it to the documentation. However, check if the colab works for you, because if it doesn’t work for others, then this makes no sense. In theory, it cannot fail to work, because the actions in the colab do not differ in any way from the configuration of the PC, browser, etc. If it works for one, it should work for everyone.

**Comment by Kilvoctu** [comment]
Doesn't work for me unfortunately, I get this:
![image](https://user-images.githubusercontent.com/2993060/201789571-c1a6b344-ada6-4395-8455-440b7a655d16.png)
When I restart the runtime and perform the script again it becomes
![image](https://user-images.githubusercontent.com/2993060/201790326-07cf9125-dc61-48ef-a0bc-b7cb2c0d2f63.png)

Well it's all right, I'm not too concerned about it if it works for you. 👍
For practical use in general scenario, I think user can run their desired Google Colab of Web UI, then run this application separately and connect to the Colab. While a Python environment is needed on local machine, the aiya bot itself is small lightweight application. I'll put some process like this in the documentation.

**Comment by matroxI** [comment]
> Doesn't work for me unfortunately, I get this: ![image](https://user-images.githubusercontent.com/2993060/201789571-c1a6b344-ada6-4395-8455-440b7a655d16.png) When I restart the runtime and perform the script again it becomes ![image](https://user-images.githubusercontent.com/2993060/201790326-07cf9125-dc61-48ef-a0bc-b7cb2c0d2f63.png)
> 
> Well it's all right, I'm not too concerned about it if it works for you. 👍 For practical use in general scenario, I think user can run their desired Google Colab of Web UI, then run this application separately and connect to the Colab. While a Python environment is needed on local machine, the aiya bot itself is small lightweight application. I'll put some process like this in the documentation.

Oh, haha, you should just ignore this error. Just don't click on restart runtime and everything should work.
