### ISSUE TITLE
Option to Change Default Width/Height

### ISSUE THREAD

**Issue by oculardegen** [Kilvoctu/aiyabot#74]
Hey! With the new 768 model it could be really nice to have this feature :o

**Comment by Kilvoctu** [comment]
Yeah that should be pretty simple to do, I think. I'll add that right now 👍

**Comment by Kilvoctu** [comment]
All right, I pushed an update, you can go ahead and give it a try.

It seem to work okay in my testing 🤔, if there's any bugs you can follow up 👀
