### ISSUE TITLE
JSONDecodeError when switching models

### ISSUE THREAD

**Issue by Subash-Chandra** [Kilvoctu/aiyabot#77]
I have 2 models that I put in the bot. MJ4 and SD. If I load the model manually in the WebUI, and then run the discord /draw command, it works perfectly fine. If I try to switch the model using the discord bot, it says 

`txt2img failed
Expecting value: line 1 column 1 (char 0)
None`

And the bot will refuse to work for a while, unless it is terminated and restarted.
Looking into the terminal, I see

![image](https://user-images.githubusercontent.com/29782637/208281365-4dce2961-3ebb-4c77-a6bb-f3e01fac534d.png)

JSONDecodeError when switching models, error in Line 1.

I'm fairly sure my models.csv is formatted correctly. Not sure what other problems could cause this error. Any thoughts?

**Comment by Kilvoctu** [comment]
What does it say on WebUI console log?
I usually get that error when I "out of memory" when swapping model, but it could be something else.

**Comment by Kilvoctu** [comment]
Did you try restarting the WebUI, then restarting bot afterward? Sometimes I have issues when adding new models to models.csv without restarting WebUI. 
Also when you run the command from bot, can you confirm at that time in WebUI console log that it's trying to switch to the correct model? What the command does is send an API call to WebUI's "options" endpoint, then waits for the response after /draw. 

That said, I checked my Discord server history, and each time this error happened it was my machine out of RAM (I like to comment in there when it happens), so I'm not sure what else it could be 🤔

**Comment by Kilvoctu** [comment]
That's weird, if using the same model, then webui shouldn't swap.

You can see here I run two commands for a voxel model (top is bot log, bottom is webui log). The webui will switch to it for the first generation, then stay on the model for the second.
![image](https://user-images.githubusercontent.com/2993060/208322287-3f6aa2fe-91b2-49d3-a5e1-c192477b760c.png)

It's possible your models.csv is formatted incorrectly in some way, but I'm not sure how to troubleshoot without seeing the log of events on webui side.

**Comment by Kilvoctu** [comment]
Ah, I see. Glad you got it working haha
