### ISSUE TITLE
Error on local host

### ISSUE THREAD

**Issue by Pyrotuna** [Kilvoctu/aiyabot#8]
Forgive me if its a fucky-wucky by me, I followed the install/use steps and its throwing this error

```
aiyabot-main\env\lib\site-packages\requests\sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for '192.168.100.105:7860/login'
```

it is worth mentioning that 192.168.100.105:7860/login shows "Method Not Allowed"

**Comment by Kilvoctu** [comment]
Your local host URL should be `https://127.0.0.1:7860` if you didn't change the port. You have to put in the whole address in ".env". If you leave `URL= ` blank, it should default to that.
Also, the bot does have to be running on the same machine as the web ui if you're using the commandline argument `--listen`.

**Comment by Pyrotuna** [comment]
It was indeed my fucky-wucky all along, web-ui's --listen default's to 0.0.0.0 and that confused me, but it was the lack of https: at the beginning that was the problem.
That said, it is worth mentioning tho that using https, errors 
`
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=7860): Max retries exceeded with url: /login (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))
`

but after a quick google search, it might be a 'urllib3' bug (?) and changing it to http solves it, in case anyone runs a similar problem
