### ISSUE TITLE
Can't generate edited prompt despite using max prompt steps

### ISSUE THREAD

**Issue by X3n0nP0w3r3d** [Kilvoctu/aiyabot#87]
When trying to edit an image (🖋️) using 50 steps (50 is max_steps) the bot will tell you that 50 steps is beyond the boundary (0-50) despite 50 being the upper limit.

**viewhandler.py > Line 144**
`if 0 < int(line.split(':', 1)[1]) < max_steps:` 

Instead, should be:
`if 0 < int(line.split(':', 1)[1]) <= max_steps:` 

This change seems to fixes the issue for me.

**Comment by Kilvoctu** [comment]
Whoops, yea that was careless of me 😅
I'll push that fix now, thanks for the report 👍
