### ISSUE TITLE
Gen-Stop

### ISSUE THREAD

**Issue by ghost** [Kilvoctu/aiyabot#98]
It appears that there is a problem with your image generation system when multiple users are trying to use it at the same time. When one user is already generating an image and another user starts a new one, it cancels the first user's generation and doesn't put it in a queue, resulting in a incomplete image.

**Comment by Kilvoctu** [comment]
Can you give some more information on how to replicate this? 🤔  
Any info from console log. Which commit of Web UI and AIYA are you running? Which commands were run? Were any of the buttons used? Did you check the PNG info of the incomplete images and re-generated them in Web UI? Any information that can help.

This is the first report I've seen of this. Theoretically it should not be possible for AIYA to interrupt a generation (she doesn't have access to the `/sdapi/v1/interrupt` API endpoint), and she doesn't generate images themselves; the Web UI does.  
If any task is sent to the Web UI, it should finish in theory, regardless of what's in AIYA's queue.  

I've seen AIYA in production on AI art-focused Discord server with 100s members, and I've not seen an issue like this 🤔

**Comment by Kilvoctu** [comment]
> Sorry for opening the bug-report.

It's all right, lol, I was just shocked! 👀  
The queue is like the core function of AIYA; I wasn't expecting this far in her existence to see a basic feature be broken. It's a week 1 bug report, or maybe right after the [queue code rewrite](https://github.com/Kilvoctu/aiyabot/pull/89).  

That said, people have found niche use cases to break AIYA before, such as this one ce80bb361de49e3a6fb68c843eff1261a0392fd9
