### ISSUE TITLE
Autocomplete not showing models from model.csv

### ISSUE THREAD

**Issue by Suhaib10** [Kilvoctu/aiyabot#99]
Updated to newer commit of sd-webui and some reason autocomplete and /tips wont show the models in my list, just shows the last one.
![image](https://user-images.githubusercontent.com/7987472/215378297-2f6eafca-4881-4fbb-b5ae-6a55a0e0bd73.png)

It was working fine with the commit from two weeks ago

This is whats in my models.csv
display_name|model_full_name|activator_token
AnythingV3|Anything-V3.0.ckpt|
AbyssOrangeMix2|AbyssOrangeMix2.ckpt|
ProtoGenX3.4|ProtoGen_X3.4.ckpt|
BerryMix|berry_mix.ckpt|
SimpMaker3K3|SimpMaker 3k3.ckpt|
HDDream|HDDream.ckpt|
OpenJourney|openjourney-v2.ckpt|mdjrny-v4style
WildsMixv1|wildSMix_v1Alloround.ckpt|
EimisAnimeDiffusion|EimisAnimeDiffusion_1-0v.ckpt|
StablediffusionV1.5|v1-5-pruned-emaonly.ckpt|
ZombiMixV8|ZombiMix-v8.ckpt|
SeekArtMegav1|seekartmegav1.ckpt|

**Comment by Kilvoctu** [comment]
Hi, which commit of sd-webui? I only have AIYA tested up to `b7d2af8c7fa48d6eef7517a6fbc63a3507c638d4` at the moment. Idunno yet if something may have changed since then.

If you do /settings command -> refresh, does it pull all the models?

**Comment by Suhaib10** [comment]
I was on [645f4e7](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/645f4e7ef8c9d59deea7091a22373b2da2b780f2). No luck with refreshing settings, even tried starting from scratch with just two models.

Heres my sd-models

`[{"title":"Anything-V3.0.ckpt [543bcbc212]","model_name":"Anything-V3.0","hash":"543bcbc212","sha256":"543bcbc21294831c6245cd74c8a7707761e28812c690f946cb81fef930d54b5e","filename":"/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0.ckpt","config":null},{"title":"HDDream.ckpt [d97f62d17e]","model_name":"HDDream","hash":"d97f62d17e","sha256":"d97f62d17e7dad4b7b176b7241d7d3e30b62cf56e50a3c31e4ccf2abc758e984","filename":"/stable-diffusion-webui/models/Stable-diffusion/HDDream.ckpt","config":null},{"title":"ProtoGen_X3.4.ckpt [61a37adf76]","model_name":"ProtoGen_X3.4","hash":"61a37adf76","sha256":"61a37adf761fbbf4cb3d88da480216341113d0fbcf9f0f77ea71863866a9b6fc","filename":"/stable-diffusion-webui/models/Stable-diffusion/ProtoGen_X3.4.ckpt","config":null},{"title":"SimpMaker 3k3.ckpt","model_name":"SimpMaker 3k3","hash":null,"sha256":null,"filename":"/stable-diffusion-webui/models/Stable-diffusion/SimpMaker 3k3.ckpt","config":null},{"title":"berry_mix.ckpt [d9691ffffe]","model_name":"berry_mix","hash":"d9691ffffe","sha256":"d9691ffffee21e2fc9baa7d4554696385bff0a90c4fe1ed625d52ac1c18016a2","filename":"/stable-diffusion-webui/models/Stable-diffusion/berry_mix.ckpt","config":null},{"title":"sd-v1-5-inpainting.ckpt","model_name":"sd-v1-5-inpainting","hash":null,"sha256":null,"filename":"/stable-diffusion-webui/models/Stable-diffusion/sd-v1-5-inpainting.ckpt","config":null},{"title":"v1-5-pruned-emaonly.ckpt","model_name":"v1-5-pruned-emaonly","hash":null,"sha256":null,"filename":"/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt","config":null},{"title":"wildSMix_v1Alloround.ckpt","model_name":"wildSMix_v1Alloround","hash":null,"sha256":null,"filename":"/stable-diffusion-webui/models/Stable-diffusion/wildSMix_v1Alloround.ckpt","config":null},{"title":"v2-1_768-ema-pruned.ckpt","model_name":"v2-1_768-ema-pruned","hash":null,"sha256":null,"filename":"/stable-diffusion-webui/models/Stable-diffusion/v2-1_768-ema-pruned.ckpt","config":null},{"title":"openjourney-v2.ckpt","model_name":"openjourney-v2","hash":null,"sha256":null,"filename":"/stable-diffusion-webui/models/Stable-diffusion/openjourney-v2.ckpt","config":null},{"title":"EimisAnimeDiffusion_1-0v.ckpt","model_name":"EimisAnimeDiffusion_1-0v","hash":null,"sha256":null,"filename":"/stable-diffusion-webui/models/Stable-diffusion/EimisAnimeDiffusion_1-0v.ckpt","config":null},{"title":"AbyssOrangeMix2.ckpt","model_name":"AbyssOrangeMix2","hash":null,"sha256":null,"filename":"/stable-diffusion-webui/models/Stable-diffusion/AbyssOrangeMix2.ckpt","config":null},{"title":"seekartmegav1.ckpt","model_name":"seekartmegav1","hash":null,"sha256":null,"filename":"/stable-diffusion-webui/models/Stable-diffusion/seekartmegav1.ckpt","config":null},{"title":"7th_anime_v2_A.ckpt","model_name":"7th_anime_v2_A","hash":null,"sha256":null,"filename":"/stable-diffusion-webui/models/Stable-diffusion/7th_anime_v2_A.ckpt","config":null},{"title":"ZombiMix-v8.ckpt [efdf0e95e4]","model_name":"ZombiMix-v8","hash":"efdf0e95e4","sha256":"efdf0e95e4cb91eedca03ce7d52d51fb24da830599a6fed01d06380a90e8258c","filename":"/stable-diffusion-webui/models/Stable-diffusion/ZombiMix-v8.ckpt","config":null},{"title":"dreamlike-photoreal-2.0.ckpt [fc52756a74]","model_name":"dreamlike-photoreal-2.0","hash":"fc52756a74","sha256":"fc52756a74d5f371422ff99a7268cb6abb14bfc4a4de3569382cf0bd75e55d36","filename":"/stable-diffusion-webui/models/Stable-diffusion/dreamlike-photoreal-2.0.ckpt","config":null}]`

**Comment by Suhaib10** [comment]
Yes Thank you! That seems to have fixed it.
